### ISSUE TITLE
Limit Characters for Post Snippet

### ISSUE THREAD

**Issue by freedompraise** [jsolly/awesome-django-blog#365]
## Context 
When creating a post, there is a field for you to create a snippet, and it appears you can make it have limitless characters. This causes issues when the snippet would be used in further cases, as it's to lengthy and would need extra formatting

## Ideal solution (What would you like to see implemented?)

A way to limit the snippet field characters, and also make sure that the snippet is a highlight from the post. Also, a feature that automatically suggests lines to be used as snippet would be cool

**Comment by jsollynlt** [comment]
I have tried to go down this route once. The problem is that if you put any kind of media or link into the snippet, that counts as characters...so you can easily go over the limit by including links.

If the character limit could be smart enough to not count `hrefs` and stuff inside a `<video>` tag as characters, I'd be open to the enhancement.

**Comment by freedompraise** [comment]
oh! I see.

I'd try to check around for a solution
